---
- name: Configure DNS
  hosts: all
  remote_user: root
  tasks:
    - name: one
      lineinfile:
        path: /etc/resolv.conf
        insertbefore: BOF
        line: 'nameserver 185.51.200.2'

    - name: two
      lineinfile:
        path: /etc/resolv.conf
        insertbefore: BOF
        line: 'nameserver 178.22.122.100'

# ------------------------------------------------------------------------------

# - name: Install Docker
#   hosts:
#     - elk-server
#   remote_user: root
#   tasks:
#     - name: Install Docker on Ubuntu
#       include: ./docker/install.yml
#       when: (ansible_facts['distribution'] == "Ubuntu")

#   handlers:
#     - name: restart docker
#       service:
#         name: docker
#         state: restarted

# ------------------------------------------------------------------------------

# - name: Install Java 8
#   hosts:
#     - elk-server
#   remote_user: root
#   tasks:
#     - name: Install Java 8 on Ubuntu
#       include: ./java/install.yml
#       when: (ansible_facts['distribution'] == "Ubuntu")

# ------------------------------------------------------------------------------

# - name: Install Elasticsearch
#   hosts:
#     - elk-server
#   remote_user: root
#   tasks:
#     - name: Install Elasticsearch on Ubuntu
#       include: ./elastic/install.yml
#       when: (ansible_facts['distribution'] == "Ubuntu")

# ------------------------------------------------------------------------------

# - name: Install And Configure Kibana
#   hosts:
#     - elk-server
#   remote_user: root
#   tasks:
#     - name: Install And Configure Kibana on Ubuntu
#       include: ./kibana/install.yml
#       when: (ansible_facts['distribution'] == "Ubuntu")

# ------------------------------------------------------------------------------

- name: Install Nginx
  hosts: 
    - elk-server
  remote_user: root
  tasks:
    - name: Install Nginx  
      include: ./nginx/install.yml
    - name: Configure Nginx  
      include: ./nginx/config.yml
     
  handlers:
    - name: Start Nginx
      service:
        name: nginx
        state: started

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted


...