global:
  scrape_interval:     120s # By default, scrape targets every 15 seconds.
  evaluation_interval: 120s # By default, scrape targets every 15 seconds.

  external_labels:
      monitor: 'virtualization-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "alert.rules"
  # - "first.rules"
  # - "second.rules"


scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 20s
    static_configs:
        - targets: ['37.152.183.117:9090']

  - job_name: 'Elasticsearch'
    scrape_interval: 20s
    static_configs:
         - targets: ['37.152.183.117:9114']

  - job_name: 'Logstash'
    scrape_interval: 20s
    static_configs:
         - targets: ['37.152.183.117:9198']

  - job_name: 'Node Exporter'
    scrape_interval: 20s
    static_configs:
         - targets: ['37.152.183.117:9100']


alerting:
  alertmanagers:
    - static_configs:
      - targets: ["manager-node:9091"]
