version: '3'
services:
  flog:
    image:  mingrammer/flog
    container_name: flog
    restart: never
    volumes:
      - /opt/web/log/:/opt/web/log
    command:
      - 'flog -t log -f apache_combined -o /opt/web/log/apache.log -b 10485760 -p 1048576'