- name: Copy compose file
  ansible.builtin.copy:
    src: ./docker-compose.yml
    dest: /root/docker-compose.yml
    owner: root
    group: root
    mode: "0644"

- name: Create log Volume Mount Point
  command: mkdir -p  web/log/

- name: Create Prometheus Config Mount Point
  command: mkdir -p /etc/prometheus

- name: Give log  Mount Point Permission
  command: chmod 775  web/log/


- name: Up Docker Containers
  command: chdir=/root docker-compose up -d