- name: Copy compose file
  ansible.builtin.copy:
    src: ./docker-compose.yml
    dest: /root/docker-compose.yml
    owner: root
    group: root
    mode: "0644"

- name: Create log Volume Mount Point
  command: mkdir -p  /opt/web/log/


- name: Give log  Mount Point Permission
  command: chmod 775  /opt/web/log/


- name: Up Docker Containers
  command: chdir=/root docker-compose run flog flog -t log -f apache_combined -o /opt/web/log/apache.log -b 10485760 -p 1048576